- name: variable level ansible
  hosts: local
  connection: local
  vars:
    username: uday
    mobile: 929090
    email: uday@gmail.com
  tasks:
    - name: print the details
      vars:
        username: kiran
        mobile: 929090
        email: kiran@gmail.com
      ansible.builtin.debug:
        msg: "username is {{ username}} mobile is {{ mobile}} email is {{ email }}"
